spring:
  data:
    mongodb:
      uri: mongodb+srv://<username>:<password>@clustertest.bq94y.mongodb.net/crudmongodb?retryWrites=true&w=majority

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
